#%RAML 1.0 NamedExample
OrderListExample:
        Region: Central America and the Caribbean
        Country: Antigua and Barbuda
        Item Type: Baby Food
        Sales Channel: Online
        Order Priority: M
        Order Date: 12/20/2013
        Order ID: 957081544
        Ship Date: 01/11/2014
        Units Sold: 552
        Unit Price: 255.28
        Unit Cost: 159.42
        Total Revenue: 140914.56
        Total Cost: 87999.84
        Total Profit: 52914.72