#%RAML 1.0 NamedExample
ShipmentListExample:
        Region: Central America and the Caribbean
        Country: Antigua and Barbuda
        Item Type: Baby Food
        Ship Date: 01/11/2014
        Total Cost: 87999.84